services:
  microservice:
    build:
      context: .
      dockerfile: microservice/Dockerfile
    ports:
      - "8000:8000"
    environment:
      MODEL_PATH: /app/data_science/modelo/modelo_final.joblib

  backend:
    build:
      context: .
      dockerfile: backend/Dockerfile
    ports:
      - "8081:8081"
    environment:
      DATASCIENCE_BASE_URL: http://microservice:8000
    depends_on:
      - microservice
    volumes:
      - backend_data:/app/data

volumes:
  backend_data:

